### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by bob-fornal** [Naveed89-tech/Three-column-component#1]
In looking through the content, I noticed that your `@media` had overlaps where you were setting `max-width` across all and given that ... this would be a better pattern. The two here do essentially what you had previously (there was in issue if the width got REALLY SMALL). I converted to PX to allow for quicker identification of what's happening.

```css
/* Mobile design  */
/******************/
@media (min-width: 500px) and (max-width: 672px) {
  html {
    font-size: 56.25%;
  }
  .car {
    padding: 2rem 1.6rem;
    max-width: 30rem;
  }
  .content {
    padding-top: 1.2rem;
    padding-bottom: 1.4rem;
    max-width: 80%;
  }
  .btn {
    margin-top: 1.4rem;
  }
}
/*****************/
@media (max-width: 499px) {
  html {
    font-size: 50%;
  }
  .container {
    flex-direction: column;
  }
  .car {
    padding: 1.4rem;
    /* max-width: rem; */
  }
  .primary-heading {
    padding-top: 2.4rem;
    font-size: 1.8rem;
  }
  .content {
    font-size: 1.4rem;
    max-width: 90%;
  }
  .btn {
    margin-top: 2rem;
    margin-bottom: 1.6rem;
  }
  .logo {
    width: 4rem;
    height: auto;
  }
}
```

I didn't dig in too much further. The remainder of the code is pretty straight forward. Good work.
